sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

matrix:
  include:
    - env: MAVEN_PROFILE="apache-2.0.0"
    - env: MAVEN_PROFILE="apache-2.1.0"
    - env: MAVEN_PROFILE="apache-2.2.0" DEPLOY_PROFILE="true"
    - env: MAVEN_PROFILE="apache-2.3.0"
    - env: MAVEN_PROFILE="cloudera-2.2.0.cloudera1"

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P$MAVEN_PROFILE

script:
  - mvn help:active-profiles -P$MAVEN_PROFILE
  - |
    if [ "$SKIP_TESTS" != "true" ]; then 
      mvn clean verify -P$MAVEN_PROFILE; 
    else
      echo "SKIPPING TESTS";
    fi
  - |
    if [ "$DEPLOY_PROFILE" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && ( [ -n "$TRAVIS_TAG" ] || [ "$TRIGGER_DEPLOYMENT" == "true" ] ); then 
      echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import;
      echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust;
      mvn clean deploy --settings .maven.xml -P$MAVEN_PROFILE -Prelease -DskipTests;
    else
      echo "SKIPPING DEPLOYMENT";
    fi
